# 4. Gaussian Elimination

A basic understanding of python and numpy arrays is useful for understanding the code snippets.

1. [Basics](#1.-Basics)
1. [Solving A Linear System](#2.-Solving-A-Linear-System)
1. [LU Factorization](#3.-LU-Factorization)
1. [Solving Ax = b](#3.-Solving-Ax-=-b)

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## 1. Basics

In mathematics, a **system of linear equations** is a collection of two or more linear equations involving the same set of variables. For example:

$
\begin{array}{}
3x & + & 2y & - & z & = & 1 \\
2x & - & 2y & + & 4z & = & -2 \\
-x & + & \frac{1}{2}y & - & z & = & 0
\end{array}
$

![](https://notebooks.azure.com/menziess/libraries/Python-Linear-Algebra/raw/res%2FLinear_system.png)
A linear system in three variables determines a collection of planes. The intersection point is the solution.

$
\begin{array}{}
x & = & 1 \\
y & = & -2 \\
z & = & -2
\end{array}
$

Such a system of linear equations can be written as:

$
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2 \\
\qquad\vdots\qquad\vdots\\
a_{m1}x_1 + a_{m2}x_2 + \cdots + a_{mn}x_n = b_m \\
$

Which can be expressed as a matrix vector multiplication $Ax = b$.

### 1.1 Methods For Solving A Linear System

There are several methods for solving a linear system:

- Describing the Solution
- Elimination of Variables
- Gaussian Elimination (or Row Reduction)
- Cramer's Rule
- Matrix Solution ($x = A^{-1}b$)

In Gaussian Elimination, the linear system is represented as an augmented matrix with a row for each variable:

$$
\left[
\begin{array}{ccc|c}
3 & 2 & -1 & 1 \\
2 & -2 & 4 & -2 \\
-1 & 0.5 & -1 & 0
\end{array}
\right]
$$

### 1.2 Types of Elementary Row Operations

The augmented matrix is then modified the following **three types of elementary row operations** until it reaches **reduced row echelon form**:

1. Swap the positions of two rows.
2. Multiply a row by a nonzero scalar.
3. Add to one row a scalar multiple of another.

### 1.3 Reduced Row Echelon Form

Row Echelon Form:
- all nonzero rows are above any rows of all zeroes
- a leading coefficient (pivot) is strictly to the right of the leading coefficient of the row above

Reduced Row Echelon Form:
- the matrix is in row echelon form
- every leading coefficient is 1 and is the only nonzero entry in its column

## 2. Solving A Linear System

First, we move the bottom row to the top and we multiply it by -1, because it has a leading coefficient that is conveniently one:

$
\left[
\begin{array}{ccc|c}
3 & 2 & -1 & 1 \\
2 & -2 & 4 & -2 \\
-1 & 0.5 & -1 & 0
\end{array}
\right]
\rightarrow$ 
$
\left[
\begin{array}{ccc|c}
1 & -0.5 & 1 & 0 \\
2 & -2 & 4 & -2 \\
3 & 2 & -1 & 1 \\
\end{array}
\right]
\rightarrow$

Second row, minus two times first row, and third row minus three times first row:

$
\left[
\begin{array}{ccc|c}
1 & -0.5 & 1 & 0 \\
0 & -1 & 2 & -2 \\
0 & 3.5 & -4 & 1 \\
\end{array}
\right]
\rightarrow$

Multiply second row with -1 so that the leading coefficient is one, then add half times row two to row one:

$
\left[
\begin{array}{ccc|c}
1 & -0.5 & 1 & 0 \\
0 & 1 & -2 & 2 \\
0 & 3.5 & -4 & 1 \\
\end{array}
\right]
\rightarrow$
$
\left[
\begin{array}{ccc|c}
1 & 0 & 0 & 1 \\
0 & 1 & -2 & 2 \\
0 & 3.5 & -4 & 1 \\
\end{array}
\right]
\rightarrow$

Then subtract 3.5 times row two from row three, then divide row three by 3:

$
\left[
\begin{array}{ccc|c}
1 & 0 & 0 & 1 \\
0 & 1 & -2 & 2 \\
0 & 0 & 3 & -6 \\
\end{array}
\right]
\rightarrow$
$
\left[
\begin{array}{ccc|c}
1 & 0 & 0 & 1 \\
0 & 1 & -2 & 2 \\
0 & 0 & 1 & -2 \\
\end{array}
\right]
\rightarrow$

Notice how both matrices are in **row echelon form**. Finally we add two times row three to row two to get the resulting matrix in **reduced row echelon form**:

$
\left[
\begin{array}{ccc|c}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & -2 \\
0 & 0 & 1 & -2 \\
\end{array}
\right]$

The variables are:

$
\begin{array}{}
x & = & 1 \\
y & = & -2 \\
z & = & -2
\end{array}
$

We can verify whether our answer is correct by substituting the variables:

$
\begin{array}{}
3x & + & 2y & - & z & = & 1 \\
2x & - & 2y & + & 4z & = & -2 \\
-x & + & \frac{1}{2}y & - & z & = & 0
\end{array}
$

$
\begin{array}{}
3 & + & 2 * (-2) & - & (-2) & = & 1 \\
2 & - & 2 * (-2) & + & 4 * (-2) & = & -2 \\
-1 & + & 0.5 * (-2) & - & (-2) & = & 0
\end{array}
$

## 3. LU Factorization

LU factorization is used for solving linear systems. $LU$ (lower-upper) decomposition or factorization factors a matrix as the product of a lower triangular $L$ that stores the reverse order of gaussian elimination steps, and an upper triangular $U$ matrix. Since $L$ is a unit lower triangular, its diagonal needs not be stored.

Find an LU decomposition for the matrix 
$A = \left[
\begin{array}{}
2 & 1 \\
8 & 7\\
\end{array}
\right]$

We use gaussian elimination to get a row equivalent of $A$ that is upper triangular, depicting it as a matrix multiplication of an elimination matrix $E$ with $A$:

$U =
\left[
\begin{array}{}
1 & 0 \\
4 & 1\\
\end{array}
\right]
\left[
\begin{array}{}
2 & 1 \\
8 & 7\\
\end{array}
\right]
=
\left[
\begin{array}{}
2 & 1 \\
0 & 3\\
\end{array}
\right]
$

The operation was:

$L =
\left[
\begin{array}{}
1 & 0 \\
4 & 1\\
\end{array}
\right]
$

Now the $LU$ decomposition of $A$ is:

$A = 
\left[
\begin{array}{}
2 & 1 \\
8 & 7\\
\end{array}
\right]
=
\left[
\begin{array}{}
1 & 0 \\
4 & 1\\
\end{array}
\right]
\left[
\begin{array}{}
2 & 1 \\
0 & 3\\
\end{array}
\right]
= LU
$

In [2]:
def LU_factorize(A):
    
    # Copy matrix
    LU = A.copy()
    nr_cols = LU.shape[1]
    
    # Loop over all columns, except the last one
    for i in range(nr_cols - 1):
        # Get leading coefficient to divide following rows
        alpha = LU[i, i]
        # Replace components with the elimination coefficient
        LU[i + 1:, i] = LU[i + 1:, i] / alpha
        # Calculate the outer product and subtract it from the rest of the matrix
        LU[i + 1:, i + 1:] = LU[i + 1:, i + 1:] - LU[i + 1:, i] @ LU[i, 1 + i:]        
        
    return np.tril(LU, -1) + np.identity(nr_cols), np.triu(LU)

In [3]:
A = np.matrix("2 1; 8 7")
L, U = LU_factorize(A)

print(A, "Matrix A", "\n")
print(L, "Unit lower matrix L", "\n")
print(U, "Upper matrix U", "\n")

[[2 1]
 [8 7]] Matrix A 

[[1. 0.]
 [4. 1.]] Unit lower matrix L 

[[2 1]
 [0 3]] Upper matrix U 



## 4. Solving Ax = b

Solving $Ax = b$ where $x$ is a vector of variables is hard. It's easier when $A$ is an upper or lower triangular system. That's where LU factorization comes in.

Lets find the solution for
$
x = \left[\begin{array}{}
\chi_0 \\
\chi_1 \\
\chi_2 \\
\end{array}
\right]
$
of the system
$
\left[\begin{array}{}
1 & 2 & 4 \\
3 & 8 & 14 \\
2 & 6 & 13 \\
\end{array}
\right]
\left[\begin{array}{}
\chi_0 \\
\chi_1 \\
\chi_2 \\
\end{array}
\right]
= \left[\begin{array}{}
3 \\
13 \\
4 \\
\end{array}
\right]
$

In [4]:
A = np.matrix("1 2 4; 3 8 14; 2 6 13")
x = np.array(['?', '?', '?'])
b = np.array([3, 13, 4])
print(A, x, '=', b)

[[ 1  2  4]
 [ 3  8 14]
 [ 2  6 13]] ['?' '?' '?'] = [ 3 13  4]


### 4.1 LU factorization

We want to solve $Ax = b$, we can start by factoring $A$ into $LU$, giving us $LUx = b$.

In [5]:
L, U = LU_factorize(A)
print(L, '\n')
print(U, '\n')
print(L @ U, x, '=', b)

[[1. 0. 0.]
 [3. 1. 0.]
 [2. 1. 1.]] 

[[1 2 4]
 [0 2 2]
 [0 0 3]] 

[[ 1.  2.  4.]
 [ 3.  8. 14.]
 [ 2.  6. 13.]] ['?' '?' '?'] = [ 3 13  4]


### 4.2 Forward Substitution

We know that $LUx = b$. Let $y = Ux$, then we can solve $Ly = b$ to find $y$.

In [6]:
def LU_forward_substitution(L, b):
    
    # Copy vector
    y = b.copy()
    
    # Calculate y, where we apply the elimination steps in L to b
    for i in range(len(y)):
        y[i + 1:] = y[i + 1:] - y[i] * L[i + 1:, i]
    
    return y

In [7]:
# Step 2 - Solving Ly = b to find y
y = LU_forward_substitution(L, b)
print(y)

[ 3  4 -6]


### 4.3 Backward Substitution

Now that we know $y$, we can solve $Ux = y$ to find $x$, and we're done.

In [8]:
def LU_back_substitution(U, b):

    # Copy vector
    x = b.copy()
    
    # Calculate x, starting at the bottom
    for i in reversed(range(len(x))):
        
        # The current row in U contains the coefficients of the variables
        # The bottom part of b contains the values of the variables
        # The current index of b is the coefficient x each corresponding variable
        # Finally this must be divided by the leading coefficient
        x[i] = x[i] - U[i, i + 1:] @ x[i + 1:]
        x[i] = x[i] / U[i, i]

    return x

In [9]:
x = LU_back_substitution(U, y)
print(A, '\n')
print(x, '\n')
print(A.dot(x))

[[ 1  2  4]
 [ 3  8 14]
 [ 2  6 13]] 

[ 3  4 -2] 

[[ 3 13  4]]


So, $x =
\left[\begin{array}{}
3 \\
4 \\
-2 \\
\end{array}
\right]
$.